[package]
name = "thermite"
version = "0.1.0"
authors = ["Nathan Kleyn <nathan@nathankleyn.com>"]
description = "Experimenting with a toy browser engine."
license = "MIT"
repository = "https://github.com/nathankleyn/thermite"

[dependencies]
